#include "http_resp.h"

char *main_page = "HTTP/1.0 200 OK\r\n"
                  "Content-type: text/html\r\n"
                  "\r\n"
                  "<html>"
                  "<head>"
                  "<title>Test server: Main page</title>"
                  "</head>"
                  "<body>"
                  "<h1>Welcome to main mage</h1>"
                  "<p>Please request a desired file </p>"
                  "</body>"
                  "</html>";

char *main_page2 = "HTTP/1.0 200 OK\r\n"
                   "Content-type: text/html\r\n"
                   "\r\n"
                   "<!DOCTYPE html>"
                   "<html>"
                   "<head>"
                   "<title>Test server: Main page</title>"
                   "</head>"
                   "<body>"
                   "<h1>Welcome to main mage</h1>"
                   "<p>Please request a desired file, list of files:<br> %s <br></p>"
                   "</body>"
                   "</html>";

char *http_404_content = "HTTP/1.0 404 Not Found\r\n"
                         "Content-type: text/html\r\n"
                         "\r\n"
                         "<html>"
                         "<head>"
                         "<title>File server: Not Found</title>"
                         "</head>"
                         "<body>"
                         "<h1>Not Found (404)</h1>"
                         "<p>This file has not been found in the directory</p>"
                         "</body>"
                         "</html>";

char *http_403_content = "HTTP/1.0 403 Forbidden\r\n"
                         "Content-type: text/html\r\n"
                         "\r\n"
                         "<html>"
                         "<head>"
                         "<title>Forbidden</title>"
                         "</head>"
                         "<body>"
                         "<h1>Forbidden</h1>"
                         "<p>It is not allowed to download this file</p>"
                         "</body>"
                         "</html>";
